// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADbr2QGFp-hdZEvtbp7Jm8f-U_Ecs8eMk',
    appId: '1:278803359802:web:14cb22db9b063f570ded03',
    messagingSenderId: '278803359802',
    projectId: 'arpit-rangi',
    authDomain: 'arpit-rangi.firebaseapp.com',
    databaseURL: 'https://arpit-rangi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arpit-rangi.appspot.com',
    measurementId: 'G-BLMW958H12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpogDW3aoyRbeGKFE8NAJx9p3ofSuqTPo',
    appId: '1:278803359802:android:7ea74c22887a524b0ded03',
    messagingSenderId: '278803359802',
    projectId: 'arpit-rangi',
    databaseURL: 'https://arpit-rangi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arpit-rangi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNl6bTsCMOVgcsl_YadQW8NnQEMTMj9so',
    appId: '1:278803359802:ios:7a83b64b87dc4a6c0ded03',
    messagingSenderId: '278803359802',
    projectId: 'arpit-rangi',
    databaseURL: 'https://arpit-rangi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arpit-rangi.appspot.com',
    iosBundleId: 'arpit.rangi.arpitRangi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNl6bTsCMOVgcsl_YadQW8NnQEMTMj9so',
    appId: '1:278803359802:ios:7a83b64b87dc4a6c0ded03',
    messagingSenderId: '278803359802',
    projectId: 'arpit-rangi',
    databaseURL: 'https://arpit-rangi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arpit-rangi.appspot.com',
    iosBundleId: 'arpit.rangi.arpitRangi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADbr2QGFp-hdZEvtbp7Jm8f-U_Ecs8eMk',
    appId: '1:278803359802:web:20b3f71ca1dafa900ded03',
    messagingSenderId: '278803359802',
    projectId: 'arpit-rangi',
    authDomain: 'arpit-rangi.firebaseapp.com',
    databaseURL: 'https://arpit-rangi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arpit-rangi.appspot.com',
    measurementId: 'G-60EBKHBGV6',
  );
}
